language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t henholm/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true henholm/docker-react npm run test